spring:
  ai:
    vectorstore:
      chroma:
        client:
          host: https://api.trychroma.com
          port: 443
          key-token: ck-8EnXWFG3ubhyM5o9HAj8hr8Y5UERvQ8AYL9GiwoYT2aT
        tenant-name: f67f67c5-aa2a-41f5-ba8a-ddeda867aba1
        database-name: aigc4lk
        collection-name: test_collection