spring:
  ai:
    alibaba:
      a2a:
        server:
          version: "1.0.0"
          card:
            name: commander_agent
            description: "指挥官Agent，动态感知所有子Agent的能力"
            skills:
              - id: "introducing_ingredients"
                name: "指挥中枢"
                description: "可根据用户的提问，分析交给系统的哪个agent进行处理，具有动态感知所有子Agent的能力"
                tags: [ "指挥能力", "动态感知能力" ,"任务分析拆解能力"]
            provider:
              name: "lk"
              organization: "air.com"
              url: "https://www.air.com"
        nacos:
          server-addr: 127.0.0.1:8848
          namespace: 0f18537a-2027-45f8-9a55-e837fa9fdd2a
          username: aigc4lk
          password: 123456
          registry:
            enabled: true
          discovery:
            enabled: true