spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: 0f18537a-2027-45f8-9a55-e837fa9fdd2a
        group: DEFAULT_GROUP
        username: aigc4lk
        password: 123456
        file-extension: yaml
        cluster-name: aigc4lk-commander-agent-cluster
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 0f18537a-2027-45f8-9a55-e837fa9fdd2a
        group: DEFAULT_GROUP
        username: aigc4lk
        password: 123456