spring:
  application:
    name: aigc4lk
  profiles:
    active: local
  config:
    import:
      - nacos:test.txt?refresh=true
  ai:
    dashscope:
      api-key: sk-c996bb14c60c428fb35e1f6b3741cd8e
      chat:
        options:
          model: deepseek-v3.2
  cloud:
    nacos:
      config: # 配置中心认证
        server-addr: 127.0.0.1:8848
        namespace: 5bd93e29-9881-4e0c-b948-b29814408294
        group: DEFAULT_GROUP
        username: aigc
        password: 123456
        file-extension: yaml
        cluster-name: aigc4lk-cluster
      discovery: # 服务注册与发现认证
        server-addr: 127.0.0.1:8848
        namespace: 5bd93e29-9881-4e0c-b948-b29814408294
        group: DEFAULT_GROUP
        username: aigc
        password: 123456

kind: Application


