server:
  port: 20010
spring:
  application:
    name: aigc4lk-central-agent
  config:
    import:
      - nacos:test.txt?refresh=true
  ai:
    dashscope:
      api-key: sk-c996bb14c60c428fb35e1f6b3741cd8e
      chat:
        options:
          model: deepseek-v3.2
    vectorstore:
      chroma:
        client:
          host: https://api.trychroma.com
          port: 443
          key-token: ck-8EnXWFG3ubhyM5o9HAj8hr8Y5UERvQ8AYL9GiwoYT2aT
        tenant-name: f67f67c5-aa2a-41f5-ba8a-ddeda867aba1
        database-name: aigc4lk
        collection-name: test_collection
        initialize-schema: true
    #    mcp:
    #      client:
    #        enabled: true
    #        name: saa-mcp-client
    #        toolcallback:
    #          enabled: true
    #        type: async
    #        streamable-http: # 定义 streamableHttp 的 MCP 工具
    #          connections:
    #            amap-maps:
    #              url: https://dashscope.aliyuncs.com/api/v1/mcps/code_interpreter_mcp/mcp # 从魔搭社区获取调用 url，移除尾部 endpoint,例如: https://mcp.api-inference.modelscope.net/?????????/
    #              endpoint: mcp
    #        sse: # 定义基于 sse 的 MCP 工具
    #          connections:
    #            12306-mcp:
    #              url: https://dashscope.aliyuncs.com/api/v1/mcps/code_interpreter_mcp/mcp  # 从魔搭社区获取调用 url，移除尾部 endpoint,例如: https://mcp.api-inference.modelscope.net/?????????/
    #              sse-endpoint: sse
    openai:
      api-key: sk-c996bb14c60c428fb35e1f6b3741cd8e
  cloud:
    nacos:
      config: # 配置中心认证
        server-addr: 127.0.0.1:8848
        namespace: 5bd93e29-9881-4e0c-b948-b29814408294
        group: DEFAULT_GROUP
        username: aigc
        password: 123456
        file-extension: yaml
        cluster-name: aigc4lk-central-agent-cluster
      discovery: # 服务注册与发现认证
        server-addr: 127.0.0.1:8848
        namespace: 5bd93e29-9881-4e0c-b948-b29814408294
        group: DEFAULT_GROUP
        username: aigc
        password: 123456

kind: Application


