logging.level.com.air=DEBUG
logging.level.com.alibaba.cloud.ai=INFO
logging.level.org.springframework.ai=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n