management.endpoints.web.exposure.include=health,metrics,prometheus,info,circuitbreakers
management.endpoint.health.show-details=always
management.metrics.tags.application=commander-service
management.metrics.tags.version=1.0.0