spring.ai.vectorstore.chroma.client.host=https://api.trychroma.com
spring.ai.vectorstore.chroma.client.port=443
spring.ai.vectorstore.chroma.client.key-token=ck-8EnXWFG3ubhyM5o9HAj8hr8Y5UERvQ8AYL9GiwoYT2aT
spring.ai.vectorstore.chroma.tenant-name=f67f67c5-aa2a-41f5-ba8a-ddeda867aba1
spring.ai.vectorstore.chroma.database-name=aigc4lk
spring.ai.vectorstore.chroma.collection-name=test_collection