spring.ai.alibaba.a2a.nacos.server-addr=127.0.0.1:8848
spring.ai.alibaba.a2a.nacos.namespace=0f18537a-2027-45f8-9a55-e837fa9fdd2a
spring.ai.alibaba.a2a.nacos.username=aigc4lk
spring.ai.alibaba.a2a.nacos.password=123456
spring.ai.alibaba.a2a.nacos.registry.enabled=false
spring.ai.alibaba.a2a.nacos.discovery.enabled=true