spring.ai.dashscope.api-key=sk-c996bb14c60c428fb35e1f6b3741cd8e
spring.ai.dashscope.chat.options.model=deepseek-v3.2
spring.ai.mcp.client.type=async
spring.ai.mcp.client.request-timeout=60s
spring.ai.mcp.client.toolcallback.enabled=true