spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
spring.cloud.nacos.discovery.namespace=0f18537a-2027-45f8-9a55-e837fa9fdd2a
spring.cloud.nacos.discovery.group=COMMANDER_GROUP
spring.cloud.nacos.discovery.username=aigc4lk
spring.cloud.nacos.discovery.password=123456
spring.cloud.nacos.discovery.ephemeral=true

spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.cloud.nacos.config.namespace=0f18537a-2027-45f8-9a55-e837fa9fdd2a
spring.cloud.nacos.config.group=COMMANDER_GROUP
spring.cloud.nacos.config.username=aigc4lk
spring.cloud.nacos.config.password=123456
spring.cloud.nacos.config.cluster-name=aigc4lk-commander-agent-cluster
spring.cloud.nacos.config.file-extension=yaml

## 这个配置现在是写死的对应CommanderMetaConfig todo 后面再整到nacos上
spring.cloud.nacos.config.extension-configs[0].data-id=agent-platform-config.yaml
spring.cloud.nacos.config.extension-configs[0].group=COMMANDER_GROUP
spring.cloud.nacos.config.extension-configs[0].refresh=true

## 这个配置现在是写死的对应ModelRouter里面的初始化静态加载配置参数 todo 后面再整到nacos上
spring.cloud.nacos.config.extension-configs[1].data-id=model-routing-config.yaml
spring.cloud.nacos.config.extension-configs[1].group=COMMANDER_GROUP
spring.cloud.nacos.config.extension-configs[1].refresh=true