server:
  port: 12100

spring:
  application:
    name: aigc4lk-document-agent
  config:
    import:
      - nacos:common-chat-model-api-keys.properties?refreshEnabled=true&group=DEFAULT_GROUP&namespace=0f18537a-2027-45f8-9a55-e837fa9fdd2a&username=aigc4lk&password=123456
      - nacos:document-mcp-config.yaml?refreshEnabled=true&group=DOCUMENT_GROUP&namespace=0f18537a-2027-45f8-9a55-e837fa9fdd2a&username=aigc4lk&password=123456
  cloud:
    nacos:
      # Nacos 服务发现配置
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 0f18537a-2027-45f8-9a55-e837fa9fdd2a
        group: DOCUMENT_GROUP
        username: aigc4lk
        password: 123456
      # Nacos 配置中心配置
      config:
        server-addr: 127.0.0.1:8848
        namespace: 0f18537a-2027-45f8-9a55-e837fa9fdd2a
        group: DOCUMENT_GROUP
        username: aigc4lk
        password: 123456
        cluster-name: aigc4lk-document-agent-service-cluster
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
    alibaba:
      a2a:
        nacos:
          server-addr: 127.0.0.1:8848
          namespace: 0f18537a-2027-45f8-9a55-e837fa9fdd2a
          username: aigc4lk
          password: 123456
          registry:
            enabled: true          # 注册到 Nacos A2A
          discovery:
            enabled: true
        server:
          version: 0.0.1
          card:
            name: document-agent    # 必须和 @Bean name 一致
            description: 文档生成智能体，支持技术报告、分析报告、会议纪要等文档生成
            provider:
              name: lk
              organization: "air.com"
              url: "https://www.air.com"
    mcp:
      client:
        enabled: false  # 禁用 MCP 客户端自动配置 todo 临时禁止